version: '3.8'

services:
  db:
    image: postgres
    container_name: moodiz-db
    restart: always
    environment:
      POSTGRES_USER: moodiz
      POSTGRES_PASSWORD: moodiz
      POSTGRES_DB: moodiz
    ports:
      - "5432:5432"